version: '2'

services:
    boilerplatebackend:
        volumes:
            - .:/ExTest

            - /ExTest/backend/node_modules

        build:
            context: ./backend
            dockerfile: ./Dockerfile

        ports:
          - "8080:8080"
